// Estilos da tela principal (Dashboard): cabeçalho recolhível, cards de evento, pills de filtro.
import { StyleSheet } from 'react-native';
import type { useTheme } from '../../theme/ThemeContext';

export function criarStyles(theme: ReturnType<typeof useTheme>) {
  return StyleSheet.create({

    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },

    headerOverlay: {
      position: 'absolute',
      left: 0,
      right: 0,
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.xs,
      backgroundColor: theme.colors.background,
      zIndex: 20,
    },

    tituloFixo: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.lg,
      backgroundColor: theme.colors.background,
      zIndex: 25,
    },

    pillsOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.sm,
      backgroundColor: theme.colors.background,
      zIndex: 15,
    },

    botaoConfiguracoesFixo: {
      position: 'absolute',
      top: theme.spacing.lg,
      right: theme.spacing.lg,
      zIndex: 30,
      padding: theme.spacing.sm,
      borderRadius: theme.radius.pill,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },

    headerTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: theme.spacing.sm,
    },
    overline: { ...theme.typography.overline, color: theme.colors.textMuted },
    titulo: { ...theme.typography.display, color: theme.colors.textPrimary, marginTop: 4 },
    resumoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.lg,
      borderWidth: 1,
      borderColor: theme.colors.border,
      paddingVertical: theme.spacing.sm + 2,
      paddingHorizontal: theme.spacing.lg,
      marginBottom: theme.spacing.md,
    },
    resumoItem: { flex: 1, alignItems: 'center' },
    resumoDivisor: { width: 1, height: 28, backgroundColor: theme.colors.border },
    resumoNumero: { ...theme.typography.heading, fontSize: 22, color: theme.colors.textPrimary },
    resumoLabel: { ...theme.typography.overline, color: theme.colors.textMuted, marginTop: 3 },

    buscaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.xs + 2,
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.md,
      borderWidth: 1,
      borderColor: theme.colors.border,
      paddingHorizontal: theme.spacing.sm + 2,
      marginBottom: theme.spacing.md,
    },
    buscaInput: {
      flex: 1,
      paddingVertical: theme.spacing.sm,
      ...theme.typography.body,
      color: theme.colors.textPrimary,
    },
    tabsScroll: { flexGrow: 0, marginBottom: theme.spacing.md },
    tabsContent: { gap: theme.spacing.xs, paddingRight: theme.spacing.lg },

    linkLimparPassados: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.xs - 2,
      alignSelf: 'flex-start',
      marginBottom: theme.spacing.md,
    },
    linkLimparPassadosTexto: { ...theme.typography.caption, color: theme.colors.textMuted },
    tab: {
      paddingVertical: theme.spacing.xs + 3,
      paddingHorizontal: theme.spacing.sm + 6,
      borderRadius: theme.radius.pill,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceElevated,

      minWidth: theme.spacing.xl,
      alignItems: 'center',
    },
    tabAtiva: { backgroundColor: theme.colors.accent, borderColor: theme.colors.accent },
    tabTexto: { ...theme.typography.bodyMedium, color: theme.colors.textSecondary },
    tabTextoAtiva: { color: theme.colors.accentText },
    vazioContainer: { alignItems: 'center', marginTop: theme.spacing.xl + theme.spacing.md, gap: theme.spacing.md },
    vazioIconeCirculo: {
      width: 52,
      height: 52,
      borderRadius: theme.radius.pill,
      backgroundColor: theme.colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    vazio: {
      ...theme.typography.body,
      color: theme.colors.textMuted,
      textAlign: 'center',
      lineHeight: 21,
    },
    skeletonCard: { height: 68, marginBottom: theme.spacing.sm, borderRadius: theme.radius.lg },
    card: {
      flexDirection: 'row',
      alignItems: 'stretch',
      borderRadius: theme.radius.lg,
      backgroundColor: theme.colors.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.colors.border,
      overflow: 'hidden',
      marginBottom: theme.spacing.sm + 2,
      shadowColor: theme.shadow.color,
      shadowOpacity: theme.shadow.opacity,
      shadowRadius: theme.shadow.radius,
      shadowOffset: { width: 0, height: theme.shadow.offsetY },
      elevation: theme.shadow.opacity > 0 ? 2 : 0,
    },

    faixa: { width: 9, flexDirection: 'column' },

    faixaSegmento: { flex: 1 },
    cardConteudo: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      padding: theme.spacing.md,
      gap: theme.spacing.sm,
    },
    cardTituloRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    cardTitulo: { ...theme.typography.subheading, color: theme.colors.textPrimary, flexShrink: 1 },

    cardMetaTagsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: 5,
      marginTop: 5,
    },

    cardData: { ...theme.typography.caption, color: theme.colors.textSecondary },
    cardDataUrgente: { color: theme.colors.urgent, fontFamily: theme.typography.bodyMedium.fontFamily },
    cardTagPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      maxWidth: 110,
      paddingVertical: 2,
      paddingHorizontal: 7,
      borderRadius: theme.radius.pill,
    },
    cardTagBolinha: { width: 6, height: 6, borderRadius: 3 },

    cardTagTexto: { ...theme.typography.caption, color: theme.colors.textMuted },
    cardDias: { ...theme.typography.caption, color: theme.colors.textSecondary },
    cardDiasUrgente: { color: theme.colors.urgent, fontFamily: theme.typography.bodyMedium.fontFamily },

    acoesSwipeRow: { flexDirection: 'row', gap: theme.spacing.sm - 4 },
    acaoFixar: {
      width: 64,
      borderRadius: theme.radius.lg,
      marginBottom: theme.spacing.sm + 2,
      marginLeft: theme.spacing.sm,
      backgroundColor: theme.colors.surfaceElevated,
      borderWidth: 1,
      borderColor: theme.colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    acaoApagar: {
      width: 64,
      borderRadius: theme.radius.lg,
      marginBottom: theme.spacing.sm + 2,
      backgroundColor: theme.colors.urgentBg,
      borderWidth: 1,
      borderColor: theme.colors.urgent + '40',
      alignItems: 'center',
      justifyContent: 'center',
    },
    botaoNovoWrapper: {
      position: 'absolute',
      right: theme.spacing.lg,
      bottom: theme.spacing.lg + theme.spacing.xs,
    },
    botaoNovo: {
      width: 56,
      height: 56,
      borderRadius: theme.radius.pill,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: theme.glow.color,
      shadowOffset: { width: 0, height: theme.glow.offsetY },
      shadowOpacity: theme.glow.opacity,
      shadowRadius: theme.glow.radius,
      elevation: 6,
    },
  });
}
